version: "3.9"
services:
    megubot:
        container_name: megubot
        build:
            context: ./MeguBot
            dockerfile: Dockerfile
        depends_on:
            - "redis"
        ports:
            - "5000:80"
        networks:
            - megubot
    redis:
        container_name: megu-redis
        image: "redis:alpine"
        ports:
            - 6379:6379
        volumes:
            - ./volumes/redis:/data
        networks:
            - megubot
    redis-commander:
        container_name: megu-redis-commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: always
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - "8081:8081"
        networks:
            - megubot
networks:
    megubot:
        name: megu-network