//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeguBOT.Domain.Lang {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeguBOT.Domain.Lang.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anime Img.
        /// </summary>
        internal static string animeimg {
            get {
                return ResourceManager.GetString("animeimg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The entered language is not supported, the supported languages are: [en, en]..
        /// </summary>
        internal static string badlang {
            get {
                return ResourceManager.GetString("badlang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Support goes directly to your DM..
        /// </summary>
        internal static string dmhelp {
            get {
                return ResourceManager.GetString("dmhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        internal static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shows you the different command alternatives that MeguBot has..
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insult the person mentioned &lt;@name&gt; or drop a random insult..
        /// </summary>
        internal static string insult {
            get {
                return ResourceManager.GetString("insult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fuck you.
        /// </summary>
        internal static string insult1 {
            get {
                return ResourceManager.GetString("insult1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motherfucker.
        /// </summary>
        internal static string insult2 {
            get {
                return ResourceManager.GetString("insult2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a N word.
        /// </summary>
        internal static string insult3 {
            get {
                return ResourceManager.GetString("insult3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The language has been successfully changed to.
        /// </summary>
        internal static string langChange {
            get {
                return ResourceManager.GetString("langChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language change command.
        /// </summary>
        internal static string langconf {
            get {
                return ResourceManager.GetString("langconf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gets a random Megumin Image.
        /// </summary>
        internal static string meguimg {
            get {
                return ResourceManager.GetString("meguimg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gets a random NSFW Megumin Image.
        /// </summary>
        internal static string meguimgnsfw {
            get {
                return ResourceManager.GetString("meguimgnsfw", resourceCulture);
            }
        }
    }
}
